apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-role
rules:
- apiGroups:
  - security.clrslate
  resources:
  - keycloakclients
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - security.clrslate
  resources:
  - keycloakclients/status
  verbs:
  - get
  - patch
  - update